### ISSUE TITLE
Unable to show time as "elapsed"

### ISSUE THREAD

**Issue by ghost** [cbyrneee/KDiscordIPC#13]
Discord RPC question
```kt
fun Activity.timestamps(start: Long, end: Long) {
    this.timestamps = Activity.Timestamps(start, end)
}
```
The discord docs says that to show the time as "elapsed" I have to not pass the endTimeStamp, but if I don't pass it or pass it as null there is an error.
`Null can not be a value of a non-null type Long`
How do I show the time as "elapsed" instead of "remaining"?

**Comment by caoimhebyrne** [comment]
Fixed in 0c852ea - you can use `timestamps(System.currentTimeMillis())` to use an elapsed timestamp.
