### ISSUE TITLE
Use standard java 16 socket library

### ISSUE THREAD

**Issue by emyfops** [cbyrneee/KDiscordIPC#30]
Since Java 16, you can use the standard socket library instead of using junixsocket since it has issues with BSD and probably other systems

junixsocket is a native library meaning it has to be edited to work with different systems while java works everywhere

**Comment by caoimhebyrne** [comment]
Yep! I would like to support this, but it would require refactoring because I still would like to support back to Java 8.

**Comment by kohlschuetter** [comment]
@Edouard127 Out of curiosity, what problems are you seeing with junixsocket and BSD?

**Comment by emyfops** [comment]
I am not the one who is experiencing issues but we had issues with junixsocket in the past
We are planning on your your library on our project and we want to make sure that we don't have have to deal with native api issues
However after some research I have found that they support the aarch64 architecture now so we're good

**Comment by kohlschuetter** [comment]
@Edouard127 Thank you! Always feel free to raise a bug report at https://github.com/kohlschutter/junixsocket if you encounter any issues.
