### ISSUE TITLE
[Suggestion] Provide own shared flow

### ISSUE THREAD

**Issue by emyfops** [cbyrneee/KDiscordIPC#32]
Currently the library uses its own event bus, SharedFlow
In some cases you may want to use an existing SharedFlow bus instead of library's one

**Comment by caoimhebyrne** [comment]
Is there any examples you can provide of where this would be needed?

**Comment by emyfops** [comment]
In large applications with multiple modules or components, you most definitely have your own bus implementation and might be optimized for your use
It also facilitates maintenance and debugging since you now know when an event is posted into your bus
 
Having a parallel event bus makes little to no sense in these scenarios
